CREATE DATABASE IF NOT EXISTS sbdb;

USE sbdb;

CREATE TABLE users(
    idUser INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) DEFAULT NULL,
    pass VARCHAR(20) DEFAULT NULL,
    rol VARCHAR(20) DEFAULT NULL
);